// KaChat Indexer fork: raw export / import of chat message data.
//
// Dumps all stored state — chat/handshake/payment/self-stash/group content AND push
// registrations (device tokens + watched-address/group/primary reverse indexes) — as a single
// file, one line per record: `<partition> <key_hex> <value_hex>`. Import restores the exact bytes
// into the same partitions, so one file rebuilds another instance's full state, no re-parsing or
// per-address paging. Only re-derivable node-sync state is excluded: the block/acceptance index
// (regenerated by re-scanning the chain) and the `metadata` sync cursor / `pending_sender_resolution`
// working state (importing a stale cursor would make a restored node skip re-scanning).

use axum::body::Bytes;
use axum::extract::State;
use axum::http::{StatusCode, header};
use axum::response::IntoResponse;
use axum::Json;
use fjall::{PartitionCreateOptions, TxKeyspace};

/// Message-content partitions that carry chat history (verbatim names from indexer-db).
pub const EXPORT_PARTITIONS: &[&str] = &[
    "handshake_by_sender",
    "handshake_by_receiver",
    "tx-id-to-handshake",
    "contextual_message_by_sender",
    // No-handshake messaging (KaChat 5.2): the inbox-tag index for dm discovery. Included so
    // export/import round-trips a full store (the sender value is re-derivable, but exporting it
    // keeps imports self-contained without re-running sender resolution).
    "contextual_message_by_inbox",
    "tx-id-to-contextual-message",
    "payment_by_sender",
    "payment_by_receiver",
    "tx_id_to_payment",
    "self_stash_by_owner",
    "tx-id-to-self-stash",
    // Group chat partitions (added with the group+push branch).
    "group_message_by_blinded_group_id",
    "tx-id-to-group-message",
    "group_sender_binding",
    "group_control_by_sender",
    "group_control_by_recipient",
    "tx-id-to-group-control",
    // Push registrations + their reverse indexes, so export/import fully round-trips push
    // delivery state (device tokens, watched addresses/groups, primary-address routing). These
    // are written together by PushRegistry::register; the index partitions are key-only (empty
    // value), which the import parser already tolerates. Not node-sync state — real stored state.
    "device_registration",
    "watched_address_to_device",
    "watched_group_id_to_device",
    "primary_address_to_device",
];

#[derive(Clone)]
pub struct ExportApi {
    tx_keyspace: TxKeyspace,
}

impl ExportApi {
    pub fn new(tx_keyspace: TxKeyspace) -> Self {
        Self { tx_keyspace }
    }
}

/// GET /stats — this indexer's slice of the Kaspa Hub → KaChat Stats screen: the chat-family
/// transaction counts it holds (comm/handshake/pay/gcomm/gctl/self_stash). Counts come from the
/// one-entry-per-tx `tx-id-to-*` partitions via approximate_len (O(1)-ish; exact enough for a
/// dashboard). The KaPosts/chess/public-chat categories are served by the content indexer, which
/// aggregates this endpoint. All-time totals only; the app shows a dash for the rolling windows.
pub async fn get_stats(State(state): State<ExportApi>) -> impl IntoResponse {
    let count = |name: &str| -> u64 {
        state
            .tx_keyspace
            .open_partition(name, PartitionCreateOptions::default())
            .map(|p| p.approximate_len() as u64)
            .unwrap_or(0)
    };
    // total from approximate_len (unchanged); 24h/7d from the cached window scan (omitted while
    // the cache is still warming). Clamp the windows to total so last24h <= last7d <= total holds
    // even though total is an approximate count and the windows are exact.
    let category = |cat: &'static str, tx_id_partition: &str| -> serde_json::Value {
        let total = count(tx_id_partition);
        let mut obj = serde_json::Map::new();
        obj.insert("total".to_string(), serde_json::json!(total));
        if let Some((d1, d7)) = crate::stats_windows::windows_for(cat) {
            let d7 = d7.min(total);
            let d1 = d1.min(d7);
            obj.insert("last24h".to_string(), serde_json::json!(d1));
            obj.insert("last7d".to_string(), serde_json::json!(d7));
        }
        serde_json::Value::Object(obj)
    };
    let categories = serde_json::json!({
        "messages":      category("messages", "tx-id-to-contextual-message"),
        "handshakes":    category("handshakes", "tx-id-to-handshake"),
        "payments":      category("payments", "tx_id_to_payment"),
        "groupMessages": category("groupMessages", "tx-id-to-group-message"),
        "groupUpdates":  category("groupUpdates", "tx-id-to-group-control"),
        "selfStash":     category("selfStash", "tx-id-to-self-stash"),
    });
    (StatusCode::OK, Json(serde_json::json!({ "categories": categories }))).into_response()
}

/// GET /export — dump every message-content partition as `<partition> <key_hex> <value_hex>`.
pub async fn export_all(State(state): State<ExportApi>) -> impl IntoResponse {
    let built = tokio::task::spawn_blocking(move || -> anyhow::Result<Vec<u8>> {
        let mut out: Vec<u8> = Vec::new();
        let rtx = state.tx_keyspace.read_tx();
        for name in EXPORT_PARTITIONS {
            let part = state
                .tx_keyspace
                .open_partition(name, PartitionCreateOptions::default())?;
            for kv in rtx.iter(&part) {
                let (k, v) = kv?;
                out.extend_from_slice(name.as_bytes());
                out.push(b' ');
                out.extend_from_slice(faster_hex::hex_string(&k).as_bytes());
                out.push(b' ');
                out.extend_from_slice(faster_hex::hex_string(&v).as_bytes());
                out.push(b'\n');
            }
        }
        Ok(out)
    })
    .await;

    match built {
        Ok(Ok(bytes)) => (
            StatusCode::OK,
            [
                (header::CONTENT_TYPE, "application/octet-stream"),
                (
                    header::CONTENT_DISPOSITION,
                    "attachment; filename=\"kachat-chat-export.txt\"",
                ),
            ],
            bytes,
        )
            .into_response(),
        _ => (StatusCode::INTERNAL_SERVER_ERROR, "export failed").into_response(),
    }
}

/// POST /import-file — restore records from an exported dump. Body is the raw file.
pub async fn import_file(State(state): State<ExportApi>, body: Bytes) -> impl IntoResponse {
    let data = body.to_vec();
    let res = tokio::task::spawn_blocking(move || -> anyhow::Result<(usize, usize)> {
        let mut parts = std::collections::HashMap::new();
        for name in EXPORT_PARTITIONS {
            parts.insert(
                *name,
                state
                    .tx_keyspace
                    .open_partition(name, PartitionCreateOptions::default())?,
            );
        }
        let mut wtx = state.tx_keyspace.write_tx()?;
        let mut imported = 0usize;
        let mut skipped = 0usize;
        for line in data.split(|&b| b == b'\n') {
            if line.is_empty() {
                continue;
            }
            // Strip only a trailing CR (tolerate CRLF files) — NOT spaces, because key-only
            // partitions store an empty value, so those lines legitimately end with a space
            // (name key ""), which must still split into three fields.
            let line = match std::str::from_utf8(line) {
                Ok(l) => l.strip_suffix('\r').unwrap_or(l),
                Err(_) => {
                    skipped += 1;
                    continue;
                }
            };
            let mut it = line.split(' ');
            let (Some(name), Some(k_hex), Some(v_hex), None) =
                (it.next(), it.next(), it.next(), it.next())
            else {
                skipped += 1;
                continue;
            };
            let Some(part) = parts.get(name) else {
                skipped += 1;
                continue;
            };
            let (Ok(k), Ok(v)) = (decode_hex(k_hex), decode_hex(v_hex)) else {
                skipped += 1;
                continue;
            };
            wtx.insert(part, k, v);
            imported += 1;
        }
        if wtx.commit()?.is_err() {
            anyhow::bail!("commit conflict");
        }
        Ok((imported, skipped))
    })
    .await;

    match res {
        Ok(Ok((imported, skipped))) => (
            StatusCode::OK,
            format!("{{\"imported\":{imported},\"skipped\":{skipped}}}"),
        )
            .into_response(),
        _ => (StatusCode::INTERNAL_SERVER_ERROR, "{\"error\":\"import failed\"}").into_response(),
    }
}

/// POST /personal/purge-all — wipe every stored chat record from all message partitions.
/// Used by the admin dashboard's personal-mode purge: clear the shared store, then let
/// personal mode re-accumulate only the operator's own data (and backfill via import-by-address).
pub async fn purge_all(State(state): State<ExportApi>) -> impl IntoResponse {
    let res = tokio::task::spawn_blocking(move || -> anyhow::Result<usize> {
        let mut removed = 0usize;
        for name in EXPORT_PARTITIONS {
            let part = state
                .tx_keyspace
                .open_partition(name, PartitionCreateOptions::default())?;
            let keys: Vec<Vec<u8>> = {
                let rtx = state.tx_keyspace.read_tx();
                rtx.iter(&part)
                    .filter_map(|kv| kv.ok().map(|(k, _)| k.to_vec()))
                    .collect()
            };
            let mut wtx = state.tx_keyspace.write_tx()?;
            for k in keys {
                wtx.remove(&part, k);
                removed += 1;
            }
            if wtx.commit()?.is_err() {
                anyhow::bail!("commit conflict during purge");
            }
        }
        Ok(removed)
    })
    .await;

    match res {
        Ok(Ok(removed)) => (
            StatusCode::OK,
            format!("{{\"removed\":{removed}}}"),
        )
            .into_response(),
        _ => (StatusCode::INTERNAL_SERVER_ERROR, "{\"error\":\"purge failed\"}").into_response(),
    }
}

/// POST /self-stash-gc-orphans — permanently remove `self_stash_by_owner` index keys whose
/// payload row (`tx-id-to-self-stash`) is missing. These orphans made `/self-stash/by-owner`
/// pages 500 before the read-path fix; this drops the dead index entries for good. Runs inside
/// the indexer's own single-writer transaction (same store, no second process), so it cannot
/// corrupt the LSM. Idempotent: a second run scans and removes nothing.
pub async fn gc_self_stash_orphans(State(state): State<ExportApi>) -> impl IntoResponse {
    let res = tokio::task::spawn_blocking(move || -> anyhow::Result<(usize, usize)> {
        let index = state
            .tx_keyspace
            .open_partition("self_stash_by_owner", PartitionCreateOptions::default())?;
        let payload = state
            .tx_keyspace
            .open_partition("tx-id-to-self-stash", PartitionCreateOptions::default())?;

        // Snapshot pass: collect index keys whose payload is missing. The tx_id is the trailing
        // 32 bytes of the by-owner key; the payload partition is keyed by that tx_id. A key that
        // is an orphan in this snapshot stays an orphan — the write pipeline always persists the
        // payload at or before the index, so a payload can never appear for it later.
        let mut scanned = 0usize;
        let orphans: Vec<Vec<u8>> = {
            let rtx = state.tx_keyspace.read_tx();
            let mut acc = Vec::new();
            for kv in rtx.iter(&index) {
                let (k, _) = kv?;
                scanned += 1;
                if k.len() < 32 {
                    continue;
                }
                let tx_id = &k[k.len() - 32..];
                if rtx.get(&payload, tx_id)?.is_none() {
                    acc.push(k.to_vec());
                }
            }
            acc
        };

        // Removal pass: single write transaction, serialized with the live indexer's own writes.
        let mut removed = 0usize;
        if !orphans.is_empty() {
            let mut wtx = state.tx_keyspace.write_tx()?;
            for k in orphans {
                wtx.remove(&index, k);
                removed += 1;
            }
            if wtx.commit()?.is_err() {
                anyhow::bail!("commit conflict during self-stash gc");
            }
        }
        Ok((scanned, removed))
    })
    .await;

    match res {
        Ok(Ok((scanned, removed))) => (
            StatusCode::OK,
            format!("{{\"scanned\":{scanned},\"orphans_removed\":{removed}}}"),
        )
            .into_response(),
        _ => (
            StatusCode::INTERNAL_SERVER_ERROR,
            "{\"error\":\"self-stash gc failed\"}",
        )
            .into_response(),
    }
}

fn decode_hex(s: &str) -> anyhow::Result<Vec<u8>> {
    if s.len() % 2 != 0 {
        anyhow::bail!("odd hex");
    }
    let mut out = vec![0u8; s.len() / 2];
    faster_hex::hex_decode(s.as_bytes(), &mut out)?;
    Ok(out)
}
