#this file allows pre-caching of target dir on host, so consecutive builds are blazing fast
#possibly need to remove target from .dockerignore to work properly
FROM rust:1.89.0-alpine3.20 AS pre-builder
RUN apk add --no-cache pcc-libs-dev musl-dev pkgconfig openssl-dev openssl-libs-static curl

FROM pre-builder AS builder
WORKDIR /usr/src/build

RUN cargo build --release
RUN cp /usr/src/build/target/release/indexer /usr/src/indexer

FROM alpine:3.20

WORKDIR /usr/src

COPY --from=builder /usr/src/indexer .

CMD ["./indexer"]
